properties:
  configuration:
    ingress:
      external: false
      targetPort: 3128
      transport: auto
  template:
    containers:
    - name: ssrfproxy
      image: ubuntu/squid:latest
      command:
      - "/bin/bash"
      args:
      - "-c"
      - "./custom-squid/start.sh"
      resources:
        cpu: 0.5
        memory: 1Gi
      volumeMounts:
      - volumeName: ssrfproxyshare
        mountPath: /custom-squid
    scale:
      minReplicas: 1
      maxReplicas: 10
    volumes:
      - name: "ssrfproxyshare"
        storageName: "ssrfproxyshare"
        storageType: "AzureFile"