properties:
  configuration:
    ingress:
      external: false
      targetPort: 5001
      transport: tcp
  template:
    containers:
      - name: worker
        image: langgenius/dify-api:1.1.2
        resources:
          cpu: 2
          memory: 4Gi
        env:
          - name: MODE
            value: worker
          - name: LOG_LEVEL
            value: INFO
          - name: SECRET_KEY
            value: sk-9f73s3ljTXVcMT3Blb3ljTqtsKiGHXVcMT3BlbkFJLK7U
          - name: DB_PORT
            value: "5432"
          - name: DB_DATABASE
            value: dify
          - name: REDIS_PORT
            value: "6380"
          - name: REDIS_USE_SSL
            value: "true"
          - name: REDIS_DB
            value: "0"
          - name: STORAGE_TYPE
            value: azure-blob
          - name: VECTOR_STORE
            value: pgvector
          - name: PGVECTOR_PORT
            value: "5432"
          - name: PGVECTOR_DATABASE
            value: vector
          - name: INDEXING_MAX_SEGMENTATION_TOKENS_LENGTH
            value: "1000"
    scale:
      minReplicas: 1
      maxReplicas: 10
